services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirma-employees
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
